library(readxl)
Mobiles <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/1_Mobiles.xlsx")
Laptops <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/2_Laptops.xlsx")
Sports <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/3_Sports.xlsx")
Bottles <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/4_Bottles.xlsx")
Baby <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/5_Baby Products.xlsx")
Tools <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/6_Tools.xlsx")
Gym <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/7_Gym.xlsx")
Books <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/8_Books.xlsx")
Groceries <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/9_Groceries.xlsx")
Furnishing <- read_excel("~/Documents/GitHub/Consumer-trust-In-E-Commerce-In-India/Data/Clean Data/10_Home Furnishing.xlsx")
Products <- list(Baby, Books, Bottles, Furnishing, Groceries, Gym, Laptops, Mobiles, Sports, Tools)
Products <- as.data.frame(do.call(rbind, Products))
library(psych)
describe.by(Products$Trust, group = Products$...1)